# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
 if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
 end

 config.vm.define :serverTensorflow do |serverTensorflow|
  serverTensorflow.vm.box = "gt50/tensorflow"
  serverTensorflow.vm.box_version = "0.9.0"
  serverTensorflow.vm.network :private_network, ip:"192.168.100.4"
  serverTensorflow.vm.hostname = "serverTensorflow"
 end
end